site_name: Max Miliano
site_url: ""
repo_url: https://github.com/maxmx03/site
repo_name: maxmx03/site
nav:
  - Currículo: CV/index.md
  - Curso de Lua:
      Primeiros Passos:
        Introdução: Lua Guide/Getting Started/index.md
        Instalação: Lua Guide/Getting Started/installation.md
        Escolhendo uma IDE: Lua Guide/Getting Started/ide.md
        Primeiro Programa: Lua Guide/Getting Started/first-program.md
      Aprendendo o Básico:
        Declarando Variáveis: Lua Guide/Basics/variables.md
        Comentários: Lua Guide/Basics/comments.md
        Tipos de dados: Lua Guide/Basics/types.md
        Strings: Lua Guide/Basics/strings.md
        Entrada do console: Lua Guide/Basics/console.md
        Definindo Funções: Lua Guide/Basics/function.md
        Operações Aritméticas: Lua Guide/Basics/arithmetic.md
        Operadores Relacionais: Lua Guide/Basics/relational.md
        Operadores Lógicos: Lua Guide/Basics/logical.md
        Outros Operadores: Lua Guide/Basics/misc.md
        Estruturas de Controle: Lua Guide/Basics/control.md
        Estruturas de Repetição: Lua Guide/Basics/loops.md
        Estrutura de Salto: Lua Guide/Basics/goto.md
        Break e Continue: Lua Guide/Basics/break.md
      Tabelas:
        Introdução: Lua Guide/Tables/index.md
        Arrays: Lua Guide/Tables/arrays.md
        Dicionários: Lua Guide/Tables/dictionary.md
        Metatables, Metamétodos e Programação orientada a objetos: Lua Guide/Tables/metatables.md
      Biblioteca do Lua:
        String: Lua Guide/Lua Library/string.md
        Math: Lua Guide/Lua Library/math.md
        Table: Lua Guide/Lua Library/table.md
theme:
  name: material
  features:
    - content.code.copy
    - content.tabs.link.copy
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/maxmx03
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_css:
  - stylesheets/extra.css
